---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: production
  labels:
    app: image-service
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.imageservice: glob:git*
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
      - name: imageservice
        image: jonj/unicorn-io-src-services-image:gitb56725f201b6e67393e388c978972c02532a3958
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP

